name: aktuel
description: Market indirimleri ve katalogları

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Firebase paketleri
  cloud_firestore: ^0.14.3
  firebase_messaging: ^7.0.0
  firebase_core: ^0.5.2
  firebase_admob: ^0.10.2
  flutter_native_admob: ^2.1.0+3
  flutter_local_notifications: ^3.0.1+5
  #resim ve internet paketleri
  shimmer: ^1.1.2
  photo_view: ^0.10.3
  cached_network_image: ^2.3.3
  connectivity: ^2.0.2
  http:
  esys_flutter_share: ^1.0.2
  ntp: ^1.0.7
  #Veritabanı için gerekli paketler
  async: ^2.4.2
  sqflite: ^1.3.2+1
  path_provider: ^1.6.24
  shared_preferences: ^0.5.12+4
  #Bloc Yapısı için gerekli paketler
  flutter_bloc: ^6.0.5
  equatable: ^1.2.4
  get_it: ^4.0.4
  #İkonlar vs görsellik için gerekli paketler
  cupertino_icons: ^1.0.1+1
  flutter_material_pickers: ^1.7.4
  fluttertoast: ^7.0.4
  intl: ^0.16.1
  animate_do: ^1.7.3
  flutter_svg: ^0.19.2+1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
   uses-material-design: true
   assets:
    - assets/atuel.db
    - assets/images/genel.jpg
    - assets/images/ev&yapı.jpg
    - assets/images/giyim.jpg
    - assets/images/mobilya.jpg
    - assets/images/kozmetik.jpg
    - assets/images/market.jpg
    - assets/images/shop.svg
    - assets/images/brochure.svg
    - assets/images/favourite.svg
    - assets/images/wish-list.svg
    - assets/images/no-wifi.svg
    - assets/images/to-do-list.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
